<p><b>VIRGINIA SALES TAX</b><br /><br />There is a 5.3% state sales tax on orders shipped to Virginia addresses, unless accompanied by a signed exemption certificate.</p>

			<p><b>PACKING, SHIPPING and HANDLING CHARGES</b><br /><br />Packing, shipping and handling charges are based on the size and type of order. Please use the chart below to determine the cost of packing and shipping to each address.<br /><br />For merchandise totals:<br />up to $10.00, add $3.50<br />$10.01 to $30.00, add $4.50<br />$30.01 to $60.00, add $5.50<br />$60.01 to $120.00, add $6.50<br />$120.01 plus, add 5% to subtotal<br /><br />Orders are shipped in the sequence they are received. During peak season (December through April) allow 5 to 15 days to receive your order from the day you place it. We will notify you if any delay is anticipated. If you have not received your order after 30 days, please contact us and include the date of your order, your telephone number, and let us know if your check has cleared the bank.<br /><br />We ship the most economical way, usually by the U.S. Postal Service. Customers with Post Office boxes: please include a street address and a daytime telephone number in case we ship by United Parcel Service (U.P.S.).</p>
<p><b>FALL AND SPRING SEASONAL ITEMS</b> </p>
<p>For 1 Fall Item (Onions, Garlic, Ginseng and Goldenseal), add $2.00 to your shipping cost. For 2 or more items, add $4.00. </p>

			<p>For 1 Spring Items (Potatoes), add $2.00 to your shipping cost. For 2 or more items, add $4.00. </p>
			<p>For fall items, orders are tallied throughout the year for shipment beginning in mid-September and ending in late-October. We ship to northern areas first. A free 4 page growing guide is included with your shipment. Bulbs are shipped only within the 48 contiguous U.S. states.</p>
			<p>Potatoes ship directly from the farm. Shipping begins in early March to the most southern states. We cannot ship earlier than mid-March. The rest of your order ships separately.</p>
			<p><b>PRIORITY HANDLING SERVICE</b><br />
			  <br />Priority Handling guarantees that your order will be shipped by Priority Mail within 48 hours of receipt of your order (Saturday, Sunday and holidays excluded). The fee for this service is in addition to the regular packing and shipping. A daytime phone number is required.<br /><br />Rates are as follows:<br />For merchandise total:<br />up to $25.00, add $5.00<br />$25.01 to $50.00, add $7.50<br />$50.01 to $100.00, add $10.00<br />Priority handling on orders over $100.00 is subject to approval.<br />Note: Priority Handling does not apply to Fall bulb shipments or Spring potato shipments.</p>

			<p><b>SUBSTITUTIONS and BACKORDERS</b><br /><br />Substitutions: In case we sell out of a seed variety, please let us know if substitutions are acceptable, and we will supply a similar variety if available. Seeds that are available for purchase online will be sent over 99.9% of the time; however, for sweet potatoes, we may need to substitute one variety for another.<br /><br />Backorders: If it is necessary to back order an item we will hold your backorder up to a maximum of 45 days, unless other arrangements are made. In the event an item is sold out, we issue a refund or a credit according to your stated preference. Credit card orders are credited electronically to your credit card account. Canadian customers are issued a credit memo.</p>
			<p><b>CUSTOMERS OUTSIDE THE CONTINENTAL UNITED STATES </b><br /><br />
			  Alaska, Hawaii, Guam, Puerto Rico, Virgin Islands, and APO, FPO addresses: We cannot ship fall bulbs (garlic, onions, ginseng, and goldenseal) to these locations.</p>
			<p><b>CANADIAN CUSTOMERS</b></p>
            <p>For orders shipping to Canada: If only ordering seeds, add $2.00, otherwise double the shipping and handling charge.  Payment must be made in the form of a Canadian Postal Money Order in U.S. funds, or a check in U.S. funds drawn on a U.S. bank, or in cash (U.S. dollars).</p>

            <p> To receive a catalog, please send $3.00 to defray postage and printing costs.</p>We cannot ship fall bulbs or roots to Canada.<p><b>INTERNATIONAL ORDERS</b></p>
<p>To order our catalog send $5 for air mail delivery or $3 surface delivery. Payment must be in U.S. dollars (cash), international postal coupons, or a check in U.S. funds drawn on a U.S. bank.</p>
			<p>We only ship internationally to <span style="font-weight: bold;">Canada and Mexico</span>. If ordering seeds only, add $2 to the shipping and handling, otherwise double the shipping and handling. Please pay with a credit card or with a Postal Money Order payable in U.S. dollars. Because of the time, expense, and complexity involved in international shipping, <span style="font-weight: bold;">we do not ship to any other foreign countries</span>.</p>We cannot ship fall bulbs or roots to Canada.<p><b>PAYMENT METHODS</b><br /><br />

			  We accept personal checks, money orders, VISA, MasterCard, Discover, and American Express. Your credit card is charged the day you place your order, including back-ordered items and seasonal items reserved for later shipment. Your credit card information is secure when you order by phone, fax, or on-line, but we cannot be responsible for any credit card information submitted by e-mail.</p>
			<p><b>GUARANTEE</b><br /><br />We want our customers to be 100% satisfied with our seeds and products. If your purchase proves unsatisfactory we will replace the item or refund the purchase price according to your preference. For full details, see our catalog.<br /></p>
			<p><b>QUESTIONS ABOUT YOUR ORDER?</b><br /><br />
			  If you have a question about your order please call us at (540) 894-9480 or send a fax to (540) 266-1021. Please do not use e-mail for time sensitive matters since e-mail may not be checked daily. To locate your order quickly, it is helpful to have your order number, your name and address, and a daytime phone where we can reach you.</p>
			<p><b><a href="http://www.southernexposure.com/seedracks/">SEED RACKS for GARDEN CENTERS and HEALTH FOOD STORES</a></b><br /><br />
			  Many varieties of our seeds are now available wholesale to selected retail stores, garden centers, and health food stores. Please <a href="http://www.southernexposure.com/seedracks/">click here</a> to learn more about our seed rack program.</p>

			<p><b>MARKET GROWERS</b></p>
			<p>Bulk quantities are available at a discounted price for a limited number of seed varieties. These are listed both in our print catalog and on-line.</p>
